import turtle#Імпортуємо модуль turtle;
turtle.speed(12)#Задамо швидкість черепашці;
turtle.bgcolor('salmon')#Задамо задньому фону колір 'salmon';
turtle.setup(1000,1000)#Задамо розмір вікна для малювання;
turtle.hideturtle()#Сховаємо курсор черепашки;
turtle.pensize(5)#Задамо розмір лінії;
def ramka(): #Створимо рамку, яку залиємо білим кольором, та в майбутньому будем малювати в ній наш малюнок;
	turtle.begin_fill()#Початок заливки;
	turtle.fillcolor('white')#Колір заливки;
	turtle.up()#Підняти черепашку;
	turtle.goto(-360,-390)#Задамо координати;
	turtle.down()#Опустимо череппашку;
	turtle.fd(700)#Намалюєм лінію довжиною в 700 пікселів;
	turtle.left(90)#Розвернемо черепашку в ліво на 90 градусів;
	turtle.fd(700)
	turtle.left(90)
	turtle.fd(700)
	turtle.left(90)
	turtle.fd(700)
	turtle.end_fill()#Кінець заливки;
	turtle.left(90)#Повернемо черепашку в початкове положення;
ramka()
def leftbody():	#Створимо ліве вухо та частину лівого туловища.
    turtle.up()
    turtle.goto(-100,100)
    turtle.left(90)
    turtle.down()
    turtle.begin_fill()
    turtle.fillcolor('salmon')
    turtle.circle(75)
    turtle.end_fill()
    turtle.left(90)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(170, 180)#Намалюєм коло з радіусом 170, та довжиною 180 пікселів;
    turtle.end_fill()
    #Повернемо черепашку на початкове положення;
    turtle.circle(170, -180)
    turtle.left(180)  
leftbody()
def volos():#Створимо волосся;
	turtle.begin_fill()
	turtle.fillcolor('yellow')
	turtle.left(60)
	turtle.fd(30)
	turtle.right(120)
	turtle.fd(30)
	turtle.left(120)
	turtle.fd(30)
	turtle.right(120)
	turtle.fd(30)
	turtle.left(120)
	turtle.fd(30)
	turtle.right(120)
	turtle.fd(30)
	turtle.left(120)
	turtle.fd(30)
	turtle.right(120)
	turtle.fd(30)
	turtle.right(-60)
	turtle.left(180)
	turtle.fd(120)
	turtle.left(-180)
	turtle.fd(120)
	turtle.end_fill()
volos()
def rightbody():#Створимо праве вухо та праву частину туловища;	
    turtle.up()
    turtle.goto(20,100)
    turtle.right(90)
    turtle.down()
    turtle.fillcolor('salmon')
    turtle.begin_fill()
    turtle.circle(55)
    turtle.end_fill()
    turtle.right(270)
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(-170, 180)
    turtle.end_fill() 
    turtle.fd(120)
rightbody()
def nogu():#Створимо ліву та праву ногу;
	turtle.up()
	turtle.goto(210,-240)
	turtle.down()
	turtle.fd(500)
	turtle.right(90)
	turtle.circle(-60,90)
	turtle.circle(-60,-90)
	turtle.right(90)
	turtle.fd(500)
	turtle.right(90)
	turtle.circle(-60,-90)	
nogu()
def okop():#Створимо праве око;
	turtle.up()
	turtle.goto(30,-25)
	turtle.down()
	turtle.fillcolor('black')
	turtle.begin_fill()
	turtle.circle(15)
	turtle.end_fill()
	turtle.fillcolor('white')
	turtle.begin_fill()
	turtle.circle(7)
	turtle.end_fill()
okop()
def okol():#Створимо ліве око;
	turtle.up()
	turtle.goto(-120,-25)
	turtle.down()
	turtle.fillcolor('black')
	turtle.begin_fill()
	turtle.circle(25)
	turtle.end_fill()
	turtle.fillcolor('white')
	turtle.begin_fill()
	turtle.circle(10)
	turtle.end_fill()
okol()
def nic():#Створимо ніс;
	turtle.up()
	turtle.goto(-40,-80)
	turtle.down()
	turtle.fillcolor('salmon')
	turtle.begin_fill()
	turtle.circle(17)
	turtle.end_fill()
nic()
def rot():#Створимо рот;
	turtle.up()
	turtle.goto(0,-130)
	turtle.down()
	turtle.circle(80,70)
rot()
def xvict():#Створимо хвіст;
	turtle.up()
	turtle.goto(191,-198)
	turtle.down()
	turtle.right(60)
	turtle.circle(300,20)
	turtle.circle(60,100)
	turtle.circle(40,200)
	turtle.circle(20,250)
xvict()
def vucaleft():#Створимо вуса з лівої сторони туловища;
	turtle.up()
	turtle.goto(0,0)
	turtle.goto(-150,-70)
	turtle.right(70)
	turtle.down()
	turtle.fd(30)
	turtle.up()
	turtle.goto(0,0)
	turtle.goto(-150,-90)
	turtle.left(20)
	turtle.down()
	turtle.fd(30)
	turtle.up()
	turtle.goto(0,0)
	turtle.goto(-150,-110)
	turtle.left(30)
	turtle.down()
	turtle.fd(30)
vucaleft()
def vucaright():#Створимо вуса з правої сторони туловища;
	turtle.up()
	turtle.goto(110,-70)
	turtle.right(180)
	turtle.down()
	turtle.fd(30)
	turtle.up()
	turtle.goto(110,-90)
	turtle.right(20)
	turtle.down()
	turtle.fd(30)
	turtle.up()
	turtle.goto(110,-110)
	turtle.right(30)
	turtle.down()
	turtle.fd(30)
	turtle.right(-30)
vucaright()



#Модифікація роботи!
def prapor(): #Створимо прапор;
	turtle.begin_fill()
	turtle.fillcolor('yellow')
	turtle.fd(40)
	turtle.right(90)
	turtle.fd(10)
	turtle.right(90)
	turtle.fd(40)
	turtle.right(90)
	turtle.fd(10)
	turtle.end_fill()
	turtle.begin_fill()
	turtle.fillcolor('blue')
	turtle.fd(10)
	turtle.right(90)
	turtle.fd(40)
	turtle.right(90)
	turtle.fd(10)
	turtle.right(-90)#Повернемо в початкове положення, щоб запобігти обертанню прапора при кожному нажатті;
	turtle.end_fill()
fon=turtle.Screen() #Створимо новий екран на якому будемо малювати прапори. 
def move(x,y):#Створимо ф-цію для переміщення нашого прапора по заданим координатим;
	turtle.up()
	turtle.goto(x,y)
	turtle.down()
	prapor()
fon.onclick(move)#При нажатті на екран повертає координати (x,y);



